---
active_modules: [pygments, tags, blog]
author: Conrad Dean
canonical_url: http://blog.conradpdean.com/
ignore_files: ['rstblog', '.*', '_*', 'config.yml', 'Makefile', 'README', '*.conf']
modules:
    pygments:
        style: tango
